# This workflow will install ruff and uses it to lint all files.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-ruff-to-lint-code

name: lint

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - LICENSE
      - AUTHORS
      - README.md

jobs:
  lint_ruff:
    name: lint with ruff

    runs-on: ubuntu-latest

    steps:
      - name: Checkout changes
        uses: actions/checkout@v4

      - name: Set up python with poetry and install dependencies
        uses: danfimov/setup-poetry@v0.1
        with:
          python-version: '3.11'
          install-args: '--no-root --all-extras'

      - name: Lint with Ruff
        run: |
          poetry run ruff check --output-format=github --show-fixes .
